version: "3.2"

services:
    front_end:
        build: ./
        user: node
        working_dir: /
        volumes:
            - ./:/code
            - ./node_modules
        environment:
            - NODE_ENV=development
        tty: true
        command: npm test
